name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        run: |
          curl -O https://builds.dotnet.microsoft.com/dotnet/Sdk/6.0.428/dotnet-sdk-6.0.428-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.0.428-linux-x64.tar.gz -C $HOME/dotnet

          echo "##[group]Set DOTNET_ROOT and PATH"
          export DOTNET_ROOT="$HOME/dotnet"
          echo "DOTNET_ROOT=$DOTNET_ROOT"
          echo "$DOTNET_ROOT" >> $GITHUB_PATH
          echo "$DOTNET_ROOT:$DOTNET_ROOT/tools" >> $GITHUB_PATH
          echo "##[endgroup]"

          echo "##[group]Disable telemetry and set system globalization invariant"
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
          echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV
          echo "##[endgroup]"
      - name: Verify dotnet
        run: dotnet --info
      - name: Build
        run: dotnet build
      - uses: actions/upload-artifact@v4
        with:
          path: ./bin
